// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/memory-alt-geometric/CleanGeometric.tsx": () => import("../components/mockups/memory-alt-geometric/CleanGeometric.tsx"),
  "./components/mockups/memory-art-directions/BoldPrint.tsx": () => import("../components/mockups/memory-art-directions/BoldPrint.tsx"),
  "./components/mockups/memory-art-directions/OutlinedCharacter.tsx": () => import("../components/mockups/memory-art-directions/OutlinedCharacter.tsx"),
  "./components/mockups/memory-art-directions/RefinedC.tsx": () => import("../components/mockups/memory-art-directions/RefinedC.tsx"),
  "./components/mockups/memory-alt-toy/ModernToy.tsx": () => import("../components/mockups/memory-alt-toy/ModernToy.tsx"),
  "./components/mockups/memory-alt-soft/SoftDimensional.tsx": () => import("../components/mockups/memory-alt-soft/SoftDimensional.tsx"),
  "./components/mockups/memory-c-bold-silhouette/BoldSilhouetteC.tsx": () => import("../components/mockups/memory-c-bold-silhouette/BoldSilhouetteC.tsx"),
  "./components/mockups/memory-c-editorial/EditorialC.tsx": () => import("../components/mockups/memory-c-editorial/EditorialC.tsx"),
  "./components/mockups/memory-c-faithful/FaithfulC.tsx": () => import("../components/mockups/memory-c-faithful/FaithfulC.tsx"),
  "./components/mockups/memory-c-painted-toy/PaintedToyC.tsx": () => import("../components/mockups/memory-c-painted-toy/PaintedToyC.tsx"),
  "./components/mockups/memory-c-paper-layered/PaperLayered.tsx": () => import("../components/mockups/memory-c-paper-layered/PaperLayered.tsx")
};
